

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ananda Mohon Ghosh
 */
public class kMeansJFrame extends javax.swing.JFrame {

    /**
     * Creates new form kMeansJFrame
     */
    public kMeansJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        kMeansTestingjButton = new javax.swing.JButton();
        K_value_jTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        testing_X_value_jTextField = new javax.swing.JTextField();
        testing_Y_value_jTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kMeansExecutejButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        KMeans_output_jTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("K-Means Algorithm Implementation");

        kMeansTestingjButton.setText("Test");
        kMeansTestingjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kMeansTestingjButtonActionPerformed(evt);
            }
        });

        K_value_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K_value_jTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter K");

        jLabel3.setText("Test A data");

        testing_X_value_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testing_X_value_jTextFieldActionPerformed(evt);
            }
        });

        testing_Y_value_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testing_Y_value_jTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter X");

        jLabel5.setText("Enter Y");

        kMeansExecutejButton1.setText("Execute");
        kMeansExecutejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kMeansExecutejButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Training Data Set");

        KMeans_output_jTextArea.setColumns(20);
        KMeans_output_jTextArea.setRows(5);
        jScrollPane1.setViewportView(KMeans_output_jTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(testing_Y_value_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(testing_X_value_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(K_value_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(kMeansExecutejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kMeansTestingjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(K_value_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kMeansExecutejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(testing_X_value_jTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(testing_Y_value_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(kMeansTestingjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Kmeans_Class kclass = new Kmeans_Class();
    static List<List<String>> listOfLists;
    int class_found;
    private void kMeansTestingjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kMeansTestingjButtonActionPerformed
           int k = Integer.valueOf(K_value_jTextField.getText().trim());
        int testingDataSize = 100;
        float testing_array[][] = new float [testingDataSize][2];
        
        Scanner scf=null;
        try {
    	scf =new Scanner(new FileReader("C:/Users/Ananda  Mohon Ghosh/Documents/NetBeansProjects/PatternRecognitionTools/test.txt"));
	} 
        catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
		e.printStackTrace();
	}
        for (int i = 0; i < testingDataSize; i++) {
            testing_array[i][0]=scf.nextFloat();
            testing_array[i][1] =scf.nextFloat();
        }
        
        int classter[]= new int [k];
        for (int i = 0; i < k; i++) {
             classter[i]=0;
        }
        
        for (int i = 0; i < testingDataSize; i++) {
            int classNo = kclass.search_a_Data(testing_array[i][0],testing_array[i][1] );
            classter[classNo]+=1;
            
        }
        //Random rnd  =new Random();
        for (int i = 0; i <k ; i++) {
            System.out.println(classter[i]/20*100+ "%");
        }
        
           
        
    }//GEN-LAST:event_kMeansTestingjButtonActionPerformed

    private void K_value_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K_value_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_K_value_jTextFieldActionPerformed

    private void testing_X_value_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testing_X_value_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testing_X_value_jTextFieldActionPerformed

    private void testing_Y_value_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testing_Y_value_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testing_Y_value_jTextFieldActionPerformed

    private void kMeansExecutejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kMeansExecutejButton1ActionPerformed
        // TODO add your handling code here:
        
        
        kclass.execute(Integer.valueOf(K_value_jTextField.getText().trim()));
        listOfLists = kclass.showCluster();
        for (int i = 0; i < Integer.valueOf(K_value_jTextField.getText().trim()); i++) 
        {
			
            //System.out.println(listOfLists.get(i));
            KMeans_output_jTextArea.append("Class "+(i+1)+"= "+listOfLists.get(i).toString()+"\n");
			
	}
    }//GEN-LAST:event_kMeansExecutejButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kMeansJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kMeansJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kMeansJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kMeansJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kMeansJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea KMeans_output_jTextArea;
    private javax.swing.JTextField K_value_jTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kMeansExecutejButton1;
    private javax.swing.JButton kMeansTestingjButton;
    private javax.swing.JTextField testing_X_value_jTextField;
    private javax.swing.JTextField testing_Y_value_jTextField;
    // End of variables declaration//GEN-END:variables
}
